/* ZCM type definition class file
 * This file was automatically generated by zcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package craebot;
 
import java.io.*;
import java.util.*;
import zcm.zcm.*;
 
public final class teleop_t implements zcm.zcm.ZCMEncodable
{
    public long utime;
    public float linear_velocity;
    public float angular_velocity;
 
    public teleop_t()
    {
    }
 
    public static final long ZCM_FINGERPRINT;
    public static final long ZCM_FINGERPRINT_BASE = 0xfa442c814ad7cbedL;
 
    static {
        ZCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(craebot.teleop_t.class))
            return 0L;
 
        classes.add(craebot.teleop_t.class);
        long hash = ZCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(ZCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeFloat(this.linear_velocity); 
 
        outs.writeFloat(this.angular_velocity); 
 
    }
 
    public teleop_t(byte[] data) throws IOException
    {
        this(new ZCMDataInputStream(data));
    }
 
    public teleop_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != ZCM_FINGERPRINT)
            throw new IOException("ZCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static craebot.teleop_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        craebot.teleop_t o = new craebot.teleop_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.linear_velocity = ins.readFloat();
 
        this.angular_velocity = ins.readFloat();
 
    }
 
    public craebot.teleop_t copy()
    {
        craebot.teleop_t outobj = new craebot.teleop_t();
        outobj.utime = this.utime;
 
        outobj.linear_velocity = this.linear_velocity;
 
        outobj.angular_velocity = this.angular_velocity;
 
        return outobj;
    }
 
}

