// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "zcmtypes/craebot/craebot_bumper_t.h"

static int __craebot_bumper_t_hash_computed;
static uint64_t __craebot_bumper_t_hash;

uint64_t __craebot_bumper_t_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __craebot_bumper_t_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__craebot_bumper_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x9aba7df6329379d0LL
         + __int64_t_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __byte_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __craebot_bumper_t_get_hash(void)
{
    if (!__craebot_bumper_t_hash_computed) {
        __craebot_bumper_t_hash = (int64_t)__craebot_bumper_t_hash_recursive(NULL);
        __craebot_bumper_t_hash_computed = 1;
    }

    return __craebot_bumper_t_hash;
}

int __craebot_bumper_t_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const craebot_bumper_t* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].is_left_pressed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].is_right_pressed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_front_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_center_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_center_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_front_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_front_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_center_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_center_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_front_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, &(p[element].omni_ir), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int craebot_bumper_t_encode(void* buf, uint32_t offset, uint32_t maxlen, const craebot_bumper_t* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __craebot_bumper_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __craebot_bumper_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __craebot_bumper_t_encoded_array_size(const craebot_bumper_t* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __boolean_encoded_array_size(&(p[element].is_left_pressed), 1);

        size += __boolean_encoded_array_size(&(p[element].is_right_pressed), 1);

        size += __boolean_encoded_array_size(&(p[element].is_light_left), 1);

        size += __boolean_encoded_array_size(&(p[element].is_light_front_left), 1);

        size += __boolean_encoded_array_size(&(p[element].is_light_center_left), 1);

        size += __boolean_encoded_array_size(&(p[element].is_light_center_right), 1);

        size += __boolean_encoded_array_size(&(p[element].is_light_front_right), 1);

        size += __boolean_encoded_array_size(&(p[element].is_light_right), 1);

        size += __int16_t_encoded_array_size(&(p[element].light_signal_left), 1);

        size += __int16_t_encoded_array_size(&(p[element].light_signal_front_left), 1);

        size += __int16_t_encoded_array_size(&(p[element].light_signal_center_left), 1);

        size += __int16_t_encoded_array_size(&(p[element].light_signal_center_right), 1);

        size += __int16_t_encoded_array_size(&(p[element].light_signal_front_right), 1);

        size += __int16_t_encoded_array_size(&(p[element].light_signal_right), 1);

        size += __byte_encoded_array_size(&(p[element].omni_ir), 1);

    }
    return size;
}

uint32_t craebot_bumper_t_encoded_size(const craebot_bumper_t* p)
{
    return 8 + __craebot_bumper_t_encoded_array_size(p, 1);
}

int __craebot_bumper_t_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, craebot_bumper_t* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].is_left_pressed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].is_right_pressed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_front_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_center_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_center_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_front_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].is_light_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_front_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_center_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_center_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_front_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].light_signal_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, &(p[element].omni_ir), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __craebot_bumper_t_decode_array_cleanup(craebot_bumper_t* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __boolean_decode_array_cleanup(&(p[element].is_left_pressed), 1);

        __boolean_decode_array_cleanup(&(p[element].is_right_pressed), 1);

        __boolean_decode_array_cleanup(&(p[element].is_light_left), 1);

        __boolean_decode_array_cleanup(&(p[element].is_light_front_left), 1);

        __boolean_decode_array_cleanup(&(p[element].is_light_center_left), 1);

        __boolean_decode_array_cleanup(&(p[element].is_light_center_right), 1);

        __boolean_decode_array_cleanup(&(p[element].is_light_front_right), 1);

        __boolean_decode_array_cleanup(&(p[element].is_light_right), 1);

        __int16_t_decode_array_cleanup(&(p[element].light_signal_left), 1);

        __int16_t_decode_array_cleanup(&(p[element].light_signal_front_left), 1);

        __int16_t_decode_array_cleanup(&(p[element].light_signal_center_left), 1);

        __int16_t_decode_array_cleanup(&(p[element].light_signal_center_right), 1);

        __int16_t_decode_array_cleanup(&(p[element].light_signal_front_right), 1);

        __int16_t_decode_array_cleanup(&(p[element].light_signal_right), 1);

        __byte_decode_array_cleanup(&(p[element].omni_ir), 1);

    }
    return 0;
}

int craebot_bumper_t_decode(const void* buf, uint32_t offset, uint32_t maxlen, craebot_bumper_t* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __craebot_bumper_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __craebot_bumper_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int craebot_bumper_t_decode_cleanup(craebot_bumper_t* p)
{
    return __craebot_bumper_t_decode_array_cleanup(p, 1);
}

uint32_t __craebot_bumper_t_clone_array(const craebot_bumper_t* p, craebot_bumper_t* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        n += __boolean_clone_array(&(p[element].is_left_pressed), &(q[element].is_left_pressed), 1);

        n += __boolean_clone_array(&(p[element].is_right_pressed), &(q[element].is_right_pressed), 1);

        n += __boolean_clone_array(&(p[element].is_light_left), &(q[element].is_light_left), 1);

        n += __boolean_clone_array(&(p[element].is_light_front_left), &(q[element].is_light_front_left), 1);

        n += __boolean_clone_array(&(p[element].is_light_center_left), &(q[element].is_light_center_left), 1);

        n += __boolean_clone_array(&(p[element].is_light_center_right), &(q[element].is_light_center_right), 1);

        n += __boolean_clone_array(&(p[element].is_light_front_right), &(q[element].is_light_front_right), 1);

        n += __boolean_clone_array(&(p[element].is_light_right), &(q[element].is_light_right), 1);

        n += __int16_t_clone_array(&(p[element].light_signal_left), &(q[element].light_signal_left), 1);

        n += __int16_t_clone_array(&(p[element].light_signal_front_left), &(q[element].light_signal_front_left), 1);

        n += __int16_t_clone_array(&(p[element].light_signal_center_left), &(q[element].light_signal_center_left), 1);

        n += __int16_t_clone_array(&(p[element].light_signal_center_right), &(q[element].light_signal_center_right), 1);

        n += __int16_t_clone_array(&(p[element].light_signal_front_right), &(q[element].light_signal_front_right), 1);

        n += __int16_t_clone_array(&(p[element].light_signal_right), &(q[element].light_signal_right), 1);

        n += __byte_clone_array(&(p[element].omni_ir), &(q[element].omni_ir), 1);

    }
    return n;
}

craebot_bumper_t* craebot_bumper_t_copy(const craebot_bumper_t* p)
{
    craebot_bumper_t* q = (craebot_bumper_t*) malloc(sizeof(craebot_bumper_t));
    __craebot_bumper_t_clone_array(p, q, 1);
    return q;
}

void craebot_bumper_t_destroy(craebot_bumper_t* p)
{
    __craebot_bumper_t_decode_array_cleanup(p, 1);
    free(p);
}

int craebot_bumper_t_publish(zcm_t* zcm, const char* channel, const craebot_bumper_t* p)
{
      uint32_t max_data_size = craebot_bumper_t_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = craebot_bumper_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _craebot_bumper_t_subscription_t {
    craebot_bumper_t_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void craebot_bumper_t_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    craebot_bumper_t p;
    memset(&p, 0, sizeof(craebot_bumper_t));
    status = craebot_bumper_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding craebot_bumper_t!!!\n", status);
        #endif
        return;
    }

    craebot_bumper_t_subscription_t* h = (craebot_bumper_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    craebot_bumper_t_decode_cleanup (&p);
}

craebot_bumper_t_subscription_t* craebot_bumper_t_subscribe (zcm_t* zcm,
                    const char* channel,
                    craebot_bumper_t_handler_t f, void* userdata)
{
    craebot_bumper_t_subscription_t* n = (craebot_bumper_t_subscription_t*)
                       malloc(sizeof(craebot_bumper_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              craebot_bumper_t_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg craebot_bumper_t ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int craebot_bumper_t_unsubscribe(zcm_t* zcm, craebot_bumper_t_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe craebot_bumper_t_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

