"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class motor_feedback_t(object):
    __slots__ = ["utime", "left_wheel_position", "right_wheel_position", "left_wheel_speed", "right_wheel_speed"]

    def __init__(self):
        self.utime = 0
        self.left_wheel_position = 0.0
        self.right_wheel_position = 0.0
        self.left_wheel_speed = 0.0
        self.right_wheel_speed = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(motor_feedback_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qffff", self.utime, self.left_wheel_position, self.right_wheel_position, self.left_wheel_speed, self.right_wheel_speed))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != motor_feedback_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return motor_feedback_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = motor_feedback_t()
        self.utime, self.left_wheel_position, self.right_wheel_position, self.left_wheel_speed, self.right_wheel_speed = struct.unpack(">qffff", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if motor_feedback_t in parents: return 0
        tmphash = (0x99ec2ef391b3f0fb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if motor_feedback_t._packed_fingerprint is None:
            motor_feedback_t._packed_fingerprint = struct.pack(">Q", motor_feedback_t._get_hash_recursive([]))
        return motor_feedback_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

