"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class odometry_t(object):
    __slots__ = ["utime", "pose", "velocity", "pose_covariance", "velocity_covariance"]

    def __init__(self):
        self.utime = 0
        self.pose = [ 0.0 for dim0 in range(3) ]
        self.velocity = [ 0.0 for dim0 in range(3) ]
        self.pose_covariance = [ 0.0 for dim0 in range(9) ]
        self.velocity_covariance = [ 0.0 for dim0 in range(9) ]

    def encode(self):
        buf = BytesIO()
        buf.write(odometry_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>3f', *self.pose[:3]))
        buf.write(struct.pack('>3f', *self.velocity[:3]))
        buf.write(struct.pack('>9f', *self.pose_covariance[:9]))
        buf.write(struct.pack('>9f', *self.velocity_covariance[:9]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != odometry_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return odometry_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = odometry_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.pose = struct.unpack('>3f', buf.read(12))
        self.velocity = struct.unpack('>3f', buf.read(12))
        self.pose_covariance = struct.unpack('>9f', buf.read(36))
        self.velocity_covariance = struct.unpack('>9f', buf.read(36))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if odometry_t in parents: return 0
        tmphash = (0xbc3825fa8b2f5236) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if odometry_t._packed_fingerprint is None:
            odometry_t._packed_fingerprint = struct.pack(">Q", odometry_t._get_hash_recursive([]))
        return odometry_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

