"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class teleop_t(object):
    __slots__ = ["utime", "linear_velocity", "angular_velocity"]

    def __init__(self):
        self.utime = 0
        self.linear_velocity = 0.0
        self.angular_velocity = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(teleop_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qff", self.utime, self.linear_velocity, self.angular_velocity))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != teleop_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return teleop_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = teleop_t()
        self.utime, self.linear_velocity, self.angular_velocity = struct.unpack(">qff", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if teleop_t in parents: return 0
        tmphash = (0xfa442c814ad7cbed) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if teleop_t._packed_fingerprint is None:
            teleop_t._packed_fingerprint = struct.pack(">Q", teleop_t._get_hash_recursive([]))
        return teleop_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

